import torch
import numpy as np
import logging
from pathlib import Path

# --- Configuration ---
# NOTE: The VisualEmbedder saves weights to this path relative to where it runs.
# If you ran the dataset builder and rollout in the same directory, these files
# will likely be overwritten, so you must save them under unique names first!

# 1. Path to the weights file saved when the DATASET was BUILT (e.g., initial run)
DATASET_WEIGHTS_PATH = Path("/home/user/franka_ros2_ws/debug_preprocessed_images/initial_projection_weights_dataset.pt")
# 2. Path to the weights file saved when the POLICY was ROLLED OUT (e.g., second run)
ROLLOUT_WEIGHTS_PATH = Path("/home/user/franka_ros2_ws/debug_preprocessed_images/initial_projection_weights.pt")

# A quick utility function to help you rename the files after running the two steps.
def rename_files_for_comparison():
    """
    Utility to help rename the single debug file generated by VisualEmbedder.
    Run this *after* the dataset build and *before* the rollout, or manually.
    """
    temp_path = Path("debug_preprocessed_images/initial_projection_weights.pt")
    
    if temp_path.exists():
        logging.warning("Please manually rename the initial_projection_weights.pt file.")
        logging.warning(f"1. Run Dataset Builder -> Rename to {DATASET_WEIGHTS_PATH.name}")
        logging.warning(f"2. Run Rollout -> Rename to {ROLLOUT_WEIGHTS_PATH.name}")
        logging.warning("Exiting utility.")
        return False
    return True

def compare_weights():
    logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

    if not DATASET_WEIGHTS_PATH.exists() or not ROLLOUT_WEIGHTS_PATH.exists():
        logging.error("--- FATAL ERROR: WEIGHT FILES NOT FOUND ---")
        logging.error(f"Missing: {DATASET_WEIGHTS_PATH.name} or {ROLLOUT_WEIGHTS_PATH.name}")
        logging.error("Make sure you run the VisualEmbedder *twice* (dataset and rollout),")
        logging.error("and manually rename the resulting 'initial_projection_weights.pt' file to unique names between runs.")
        return

    logging.info("--- Loading and Comparing Projection Weights ---")

    try:
        # Load the two state dictionaries
        dataset_weights = torch.load(DATASET_WEIGHTS_PATH)
        rollout_weights = torch.load(ROLLOUT_WEIGHTS_PATH)
        
    except Exception as e:
        logging.error(f"Error loading files: {e}")
        return

    all_keys = set(dataset_weights.keys())
    
    if not all_keys:
        logging.error("No weights found in the loaded files.")
        return

    is_identical = True

    print("\n" + "=" * 60)
    print(f"{'Key':<30}{'Mean Abs Diff':<20}{'Max Abs Diff':<10}")
    print("-" * 60)
    
    for key in sorted(list(all_keys)):
        if key not in rollout_weights:
            logging.error(f"Key '{key}' missing in rollout weights!")
            is_identical = False
            continue

        tensor_a = dataset_weights[key]
        tensor_b = rollout_weights[key]

        if tensor_a.shape != tensor_b.shape:
            logging.error(f"Shape mismatch for {key}: {tensor_a.shape} vs {tensor_b.shape}")
            is_identical = False
            continue

        # Calculate difference
        diff = torch.abs(tensor_a - tensor_b)
        mean_abs_diff = torch.mean(diff).item()
        max_abs_diff = torch.max(diff).item()
        
        # Check for significant difference
        if mean_abs_diff > 1e-6:
            is_identical = False
            status = "❌ DIFFERENT"
        else:
            status = "✅ IDENTICAL"

        print(
            f"{key:<30}"
            f"{mean_abs_diff:<20.8f}"
            f"{max_abs_diff:<10.8f} {status}"
        )

    print("=" * 60 + "\n")

    if is_identical:
        logging.info("CONCLUSION: The projection weights are IDENTICAL.")
        logging.info("This means the random seed was set correctly for both runs.")
        logging.info("If your VFE features still differ, the problem is elsewhere.")
    else:
        logging.critical("CONCLUSION: The projection weights are SIGNIFICANTLY DIFFERENT.")
        logging.critical("This CONFIRMS the hypothesis: Random initialization is the source of the feature shift.")
        logging.critical("The fix must involve saving and loading canonical projection weights.")


if __name__ == '__main__':
    # You MUST run the VisualEmbedder twice and rename the output file 
    # for the comparison to work correctly.
    # See the renaming instructions above.
    compare_weights()