# model_pipeline/visual_embedder.py
import torch
import torch.nn as nn
from torchvision import transforms, models
import numpy as np
import cv2
import logging
from pathlib import Path

class VisualEmbedder(nn.Module):
    """
    A deterministic CNN-based visual feature extractor for RGB and depth images.
    Wraps a pretrained backbone (ResNet18 or MobileNetV3) and projects to fixed embeddings.
    """

    def __init__(
        self,
        backbone: str = "resnet18",
        device: str | None = None,
        pretrained: bool = True,
        out_dim: dict[str, int] | None = None,
        global_depth_range: tuple[float, float] | None = None,
        canonical_weights_path: Path | str | None = None,
    ):
        super().__init__()

        # --- Add Debugging Parameters ---
        self.debug_save = False
        self.debug_dir = Path("debug_preprocessed_images")
        if self.debug_save:
            self.debug_dir.mkdir(exist_ok=True)
            logging.info(f"Debug saving enabled. Images will be saved to: {self.debug_dir}")
            self.projection_weights_path = self.debug_dir / "initial_projection_weights.pt"


        # --- Device setup ---
        if device is None:
            device = "cuda" if torch.cuda.is_available() else "cpu"
        self.device = torch.device(device)
        self.backbone_name = backbone

        # --- Load backbone ---
        if backbone == "resnet18":
            weights = models.ResNet18_Weights.DEFAULT if pretrained else None

            base_model = models.resnet18(weights=weights)
            self.feat_dim = 512
            modules = list(base_model.children())[:-1]  # drop final FC
            self.encoder = nn.Sequential(*modules)
            self.post_flatten = lambda t: t.reshape(t.shape[0], -1)
        elif backbone == "mobilenet_v3_small":
            weights = models.MobileNet_V3_Small_Weights.DEFAULT if pretrained else None
            base_model = models.mobilenet_v3_small(weights=weights)
            self.feat_dim = base_model.classifier[0].in_features
            modules = list(base_model.features)
            self.encoder = nn.Sequential(*modules, nn.AdaptiveAvgPool2d((1, 1)))
            self.post_flatten = lambda t: t.reshape(t.shape[0], -1)
        else:
            raise ValueError(f"Unsupported backbone: {backbone}")

        # --- Projection layers ---
        if out_dim is None:
            out_dim = {"rgb": 256, "depth": 128}
        self.out_dim = out_dim

        self.project_rgb = nn.Linear(self.feat_dim, self.out_dim["rgb"])
        self.project_depth = nn.Linear(self.feat_dim, self.out_dim["depth"])

        if canonical_weights_path:
            p = Path(canonical_weights_path)
            if p.is_file():
                try:
                    # Load the full state dict generated by create_canonical_vfe.py
                    state_dict = torch.load(p, map_location=self.device)
                    self.load_state_dict(state_dict, strict=True)
                    logging.info(f"✅ Loaded canonical VFE weights from: {p.name}")
                except Exception as e:
                    logging.error(f"❌ Failed to load canonical VFE weights from {p.name}: {e}")
                    logging.warning("Continuing with random initialization for projection layers.")
            else:
                logging.warning(f"Canonical VFE weights path not found: {p}. Continuing with random initialization.")

        if self.debug_save:
            # Create a state dict containing only the two projection layers
            projection_state = {
                'project_rgb.weight': self.project_rgb.weight.data,
                'project_rgb.bias': self.project_rgb.bias.data,
                'project_depth.weight': self.project_depth.weight.data,
                'project_depth.bias': self.project_depth.bias.data,
            }
            # Save the initial random weights
            torch.save(projection_state, self.projection_weights_path)
            logging.info(f"Initial projection weights saved to: {self.projection_weights_path}")

        # --- Global depth range ---
        if global_depth_range:
            self.global_min_depth, self.global_max_depth = global_depth_range
        else:
            self.global_min_depth, self.global_max_depth = 0.0, 1.0  # fallback

        # --- Image normalization ---
        self.transform = transforms.Compose([
            transforms.ToPILImage(),
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])

        # --- Determinism and eval mode ---
        self.to(self.device)
        self.eval()
        torch.set_grad_enabled(False)
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True

    # ------------------------------------------------------------
    # Forward utilities
    # ------------------------------------------------------------

    @torch.no_grad()
    def embed_rgb(self, img_rgb: np.ndarray, frame_id) -> np.ndarray | None:
        """Embed a single RGB image into a fixed-length feature vector."""
        if img_rgb is None:
            return None
        # img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)


        if self.debug_save:
            # Save the BGR->RGB converted image for comparison
            save_path = self.debug_dir / f"{frame_id}_rgb_pre_transform.png"
            cv2.imwrite(str(save_path), img_rgb) # cv2 expects BGR, but we save RGB as is.
                                                # We just need the raw data array for comparison.

        t = self.transform(img_rgb).unsqueeze(0).to(self.device)


        feats = self.encoder(t)
        feats = self.post_flatten(feats)
        projected_feats = self.project_rgb(feats)
        # Squeeze and convert to numpy for logging
        output_features_numpy = projected_feats.squeeze(0).cpu().numpy()
        if self.debug_save:
            print(f"[{frame_id}] Input Stats: Shape={img_rgb.shape}, Dtype={img_rgb.dtype}, Min={img_rgb.min()}, Max={img_rgb.max()}, Mean={img_rgb.mean():.2f}")
            print(f"[{frame_id}] Tensor Stats: Min={t.min():.2f}, Max={t.max():.2f}, Mean={t.mean():.2f}")
            print(f"[{frame_id}] Output Feature Stats: Dim={output_features_numpy.shape[0]}, Min={output_features_numpy.min():.4f}, Max={output_features_numpy.max():.4f}, Mean={output_features_numpy.mean():.4f}")
        
        return output_features_numpy
    
    @torch.no_grad()
    def embed_depth(self, depth_img: np.ndarray, frame_id) -> np.ndarray | None:
        """Embed a single depth image into a fixed-length feature vector."""
        if depth_img is None:
            return None

        # Clip and normalize using global range
        dmin, dmax = self.global_min_depth, self.global_max_depth
        depth_clipped = np.clip(depth_img, dmin, dmax)
        depth_normalized = (depth_clipped - dmin) / (dmax - dmin + 1e-9)
        depth_u8 = (depth_normalized * 255.0).astype(np.uint8)

        depth_rgb = cv2.cvtColor(depth_u8, cv2.COLOR_GRAY2RGB)

        if self.debug_save:
            # Save the 3-channel grayscale depth image for comparison
            save_path = self.debug_dir / f"{frame_id}_depth_pre_transform.png"
            cv2.imwrite(str(save_path), depth_rgb)

        t = self.transform(depth_rgb).unsqueeze(0).to(self.device)
        feats = self.encoder(t)
        feats = self.post_flatten(feats)
        projected_feats = self.project_depth(feats)
        return projected_feats.squeeze(0).cpu().numpy()

    # ------------------------------------------------------------
    # TorchScript export (optional)
    # ------------------------------------------------------------

    def to_torchscript(self, sample_input_rgb: np.ndarray):
        """(Optional) TorchScript export stub."""
        example = torch.from_numpy(sample_input_rgb).unsqueeze(0).to(self.device)
        self.eval()
        raise NotImplementedError("Tracing must be done from a pipeline wrapper.")
