<?xml version="1.0"?>
<package format="3">
<name>model_pipeline</name>
<version>0.1.0</version>
<description>Dataset preprocessing and small-policy training utilities for FR3 tactile pipeline.</description>
<maintainer email="maestre.paul.antoine.q8@dc.tohoku.ac.jp">Maestre Paul</maintainer>
<license>Apache-2.0</license>


<buildtool_depend>ament_python</buildtool_depend>


<exec_depend>python3</exec_depend>
<exec_depend>rclpy</exec_depend>


<!-- Third-party python packages (install via pip into your env) -->
<exec_depend>numpy</exec_depend>
<exec_depend>opencv-python</exec_depend>
<exec_depend>scikit-learn</exec_depend>
<exec_depend>torch</exec_depend>
<exec_depend>matplotlib</exec_depend>


<export>
<build_type>ament_python</build_type>
</export>
</package>